"""empty message

Revision ID: 84e37a6d0244
Revises: 8e19a4a64f3a
Create Date: 2025-04-19 12:25:13.392317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e37a6d0244'
down_revision: Union[str, None] = '8e19a4a64f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('profile_url', sa.String(), server_default='', nullable=True))
    op.add_column('candidates', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('candidates', 'follower')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('follower', sa.VARCHAR(), server_default=sa.text("'text(0)'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'password')
    op.drop_column('candidates', 'profile_url')
    # ### end Alembic commands ###
